### PR TITLE
Re-implemented PR #8

### PR DESCRIPTION
**Pull request by choptastic**
Hi Dmitry,

So as mentioned in #8, the merge there, given its age, broke some things.

This commit will cleanly merge with the previous HEAD (https://github.com/dmitryme/erlang_localtime/commit/458cedf2a2377e1dba54bc48d81c41ff45ace2e9).

My suggestion is to revert the merge, effectively removing the previous commit from history by doing the following:

```bash
# check out previous HEAD
git checkout 458cedf

# delete the master branch from your local 
git branch -D master

# make the current commit the head of the master branch
git checkout -b master   

# force-push the current master back to github
git push origin +master
```

After doing that, this commit I've submitted will merge cleanly.

### CODE REVIEW

**Comment by choptastic** [comment]
I see that you've reverted the previously merged commit. Great! This pull request should merge cleanly now without having to clean up inconsistencies.  I ask again if you could merge this please, then I can update qdate to use this repo instead of my fork.

Thanks again!

**Comment by choptastic** [comment]
Hi, Any chance this can be merged?

**Comment by dmitryme** [comment]
done

**Comment by choptastic** [comment]
Thank you!

**Pull request merged**
